baseURL = 'https://my-blog.pages.dev/'
locale = 'zh-cn'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh'
title = '我的博客'
theme = 'blog-minimal'

[params]
description = '一个使用 GitHub、Hugo 和 Cloudflare Pages 发布的静态博客。'

[menus]
  [[menus.main]]
    name = '首页'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = '文章'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = '课程'
    url = '#'
    weight = 30

  [[menus.main]]
    name = '工具箱'
    url = '#'
    weight = 40

  [[menus.main]]
    name = '案例'
    url = '#'
    weight = 50

  [[menus.main]]
    name = '资源'
    url = '#'
    weight = 60

  [[menus.main]]
    name = '社区'
    url = '#'
    weight = 70

  [[menus.main]]
    name = '关于'
    url = '#'
    weight = 80
